# Generated by Django 4.2.7 on 2023-11-22 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_device_id_alter_platform_id_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
